In [2]:
import numpy as np
import PIL.Image as Image

pic = Image.open("/home/liw324/code/Segment/Seg-Aliasing/dataset/cityscapes/leftImg8bit/train/aachen/aachen_000000_000019_leftImg8bit.png")
pic_numpy = np.array(pic)


In [3]:
print(pic_numpy.shape)

(1024, 2048, 3)


In [4]:
import numpy as np
import PIL.Image as Image

gtFine_labelIds = Image.open("/home/liw324/code/Segment/Seg-Aliasing/dataset/cityscapes/gtFine/test/berlin/berlin_000000_000019_gtFine_labelIds.png")
gtFine_labelIds_numpy = np.array(gtFine_labelIds)


In [5]:
print(gtFine_labelIds_numpy.shape)

(1024, 2048)


In [6]:
print(np.unique(gtFine_labelIds_numpy))


[0 1 3]


In [15]:

gtFine_instanceIds = Image.open("/home/liw324/code/Segment/Seg-Aliasing/dataset/cityscapes/gtFine/train/aachen/aachen_000000_000019_gtFine_instanceIds.png")
gtFine_instanceIds_numpy = np.array(gtFine_instanceIds)
print(np.unique(gtFine_instanceIds_numpy))


[    0     1     3     4     7     8    11    17    20    21    22    23
 24000 24001 25000 26003 26004 26005 26006 26007 26008 26009 26010 33000
 33001]


In [2]:
from mmseg_custom.datasets import CityscapesDataset

dataset = CityscapesDataset(image_dir='/data/likai/cityscapes/leftImg8bit/test', 
                            mask_dir='/data/likai/cityscapes/gtFine/test', 
                            transforms=None,img_suffix='_leftImg8bit.png',
                            seg_map_suffix='_gtFine_labelIds.png',
                            )
print(len(dataset))
image, meta = dataset[0]
print(image.shape)
print(meta['imagen'])
print(meta['raw_image'].shape)
print(meta['mask'].shape)
# print(meta['mask'])
print(np.unique(meta['mask']))
print()

TypeError: __init__() got an unexpected keyword argument 'image_dir'

In [6]:
import numpy as np
import PIL.Image as Image
gtFine_instanceIds = Image.open("/home/liw324/code/Segment/Seg-Aliasing/dataset/cityscapes/gtFine/train/aachen/aachen_000000_000019_gtFine_labelIds.png")
gtFine_instanceIds_numpy = np.array(gtFine_instanceIds)
print(np.unique(gtFine_instanceIds_numpy))

# def _convert_to_label_id(result):
#     """Convert trainId to id for cityscapes."""
#     if isinstance(result, str):
#         result = np.load(result)
#     import cityscapesscripts.helpers.labels as CSLabels
#     result_copy = result.copy()
#     for trainId, label in CSLabels.trainId2label.items():
#         result_copy[result == trainId] = label.id

#     return result_copy

import cityscapesscripts.helpers.labels as CSLabels
def convert_label_ids_to_train_ids(mask):
    mask_copy = mask.copy()
    for label in CSLabels.labels:
        mask_copy[mask == label.id] = label.trainId
        
    # Set the ignored labels to 255
    mask_copy[mask_copy == 255] = 0
    
    return mask_copy

print(np.unique(convert_label_ids_to_train_ids(gtFine_instanceIds_numpy)))



[ 0  1  3  4  7  8 11 17 20 21 22 23 24 25 26 33]
[ 0  1  2  5  7  8  9 10 11 12 13 18]


/tmp/ipykernel_1267007/1458144694.py:22: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -1 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  mask_copy[mask == label.id] = label.trainId


In [6]:

# test_pipeline.py
import sys
# from mmseg_custom.datasets.pipelines import Compose
from mmseg_custom.datasets import EarthVQADataset

EarthVQADataset()

ImportError: cannot import name 'EarthVQADataset' from 'mmseg_custom.datasets' (/home/liw324/code/Segment/Seg-Aliasing/mmseg_custom/datasets/__init__.py)